
[helmRepos]
  bitnami = "https://charts.bitnami.com/bitnami"
  k8ssandra = "https://helm.k8ssandra.io/stable"
  jetstack = "https://charts.jetstack.io"
  strimzi = "https://strimzi.io/charts"
[namespaces]
  [namespaces.default]
  [namespaces.cert-manager]
  [namespaces.cassandra]
  [namespaces.kafka]
[apps]
  [apps.k8ssandra]
    namespace = "cassandra"
    enabled = true
    chart = "k8ssandra/k8ssandra"
    version = "1.3.1"
    valuesFile = "infra/k8s/values/cassandra.yaml"
  [apps.redis]
    namespace = "default"
    enabled = true
    chart = "bitnami/redis"
    version = "14.6.3"
    valuesFile = "infra/k8s/values/redis.yaml"
  [apps.rabbitmq]
    namespace = "default"
    enabled = true
    chart = "bitnami/rabbitmq"
    version = "8.16.1"
    valuesFile = "infra/k8s/values/rabbitmq.yaml"
  [apps.kafka]
    namespace = "kafka"
    enabled = true
    chart = "strimzi/strimzi-kafka-operator"
    version = "0.25.0"
