
[helmRepos]
  bitnami = "https://charts.bitnami.com/bitnami"
  sealed-secrets = "https://bitnami-labs.github.io/sealed-secrets"
  scylla = "https://scylla-operator-charts.storage.googleapis.com/stable"
  jetstack = "https://charts.jetstack.io"
[namespaces]
  [namespaces.default]
  [namespaces.cert-manager]
  [namespaces.scylla-operator]
  [namespaces.scylla-manager]
  [namespaces.scylla]

[apps]
  [apps.scylla-operator]
    namespace = "scylla-operator"
    enabled = true
    chart = "scylla/scylla-operator"
    version = "1.4.0"
  [apps.scylla-manager]
    namespace = "scylla-manager"
    enabled = true
    chart = "scylla/scylla-manager"
    version = "1.4.0"
  [apps.scylla]
    namespace = "scylla"
    enabled = true
    chart = "scylla/scylla"
    version = "1.4.0"
    valuesFile = "infra/k8s/values/scylla.yaml"
  [apps.redis]
    namespace = "default"
    enabled = true
    chart = "bitnami/redis"
    version = "14.6.3"
    valuesFile = "infra/k8s/values/redis.yaml"
  [apps.rabbitmq]
    namespace = "default"
    enabled = true
    chart = "bitnami/rabbitmq"
    version = "8.16.1"
    valuesFile = "infra/k8s/values/rabbitmq.yaml"
    
