apiVersion: v1
kind: ConfigMap
metadata:
  name: ksci
data:
  KSCI_URL: "http://ksci-api.default.svc/"
  KSCI_REDIS_HOST: "redis-master.default.svc"
  KSCI_RABBITMQ_HOST: "rabbitmq.default.svc"
  KSCI_RABBITMQ_USERNAME: "ksci"
  KSCI_CASSANDRA_HOSTS: "k8ssandra-dc1-service.cassandra.svc"
  KSCI_KAFKA_HOSTS: "ksci-kafka-brokers.kafka.svc:9092"
