apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksci-statuschange
  labels:
    app: ksci-statuschange
spec:
  selector:
    matchLabels:
      app: ksci-statuschange
  template:
    metadata:
      labels:
        app: ksci-statuschange
    spec:
      containers:
        - name: ksci-statuschange
          image: larcher/ksci-consumer
          command: ["/usr/local/bin/statuschange"]
          envFrom:
            - configMapRef:
                name: ksci
          env:
            - name: KSCI_CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: username
            - name: KSCI_CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra
                  key: password
