apiVersion: flink.k8s.io/v1beta1
kind: FlinkApplication
metadata:
  name: ksci-flink-jobdurations
  namespace: flink-operator
  annotations:
  labels:
    environment: development
spec:
  image: docker.io/larcher/ksci-flink-jobdurations:latest
  deleteMode: None
  flinkConfig:
    taskmanager.memory.network.min: 10m
    taskmanager.memory.flink.size: 500m
    taskmanager.memory.managed.fraction: 0.3
    state.backend.fs.checkpointdir: file:///checkpoints/flink/checkpoints
    state.checkpoints.dir: file:///checkpoints/flink/externalized-checkpoints
    state.savepoints.dir: file:///checkpoints/flink/savepoints
    web.upload.dir: /opt/flink
  jobManagerConfig:
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.1"
    replicas: 1
  taskManagerConfig:
    taskSlots: 2
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.1"
  flinkVersion: "1.13.2"
  jarName: "jobdurations-1.0-SNAPSHOT.jar"
  parallelism: 1
  entryClass: "onl.archer.ksci.JobDurations"
